-- Prototype Table without strict Foreign Key boundaries to seamlessly transition UI
CREATE TABLE public.mock_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  roll TEXT NOT NULL,
  type TEXT NOT NULL,
  days TEXT NOT NULL,
  reason TEXT NOT NULL,
  date TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending',
  proof_filename TEXT,
  proof_url TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Allow our frontend prototype to freely read and insert
ALTER TABLE public.mock_requests ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow anon read access" ON public.mock_requests
  FOR SELECT USING (true);

CREATE POLICY "Allow anon insert access" ON public.mock_requests
  FOR INSERT WITH CHECK (true);

CREATE POLICY "Allow anon update access" ON public.mock_requests
  FOR UPDATE USING (true);
